<a href="https://colab.research.google.com/github/ankitasinha13/Python-Practice-/blob/main/1st_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = [2,5,7,8,9]
print(np.array(a))

[2 5 7 8 9]


In [4]:
a =np.array([2,5,7,8,9])
print(a.sum())

31


In [5]:
a =np.array([2,5,6,7,8])
print(a.mean())

5.6


In [6]:
a =np.array([2,5,6,7,8])
print(a.max())

8


In [7]:
a =np.array([2,5,6,7,8])
print(a.min())

2


In [10]:
a = np.array([10,39,59,50,60])
b = np.array([30,50,46,68,89])
result = np.add(a,b)
print(result)

[ 40  89 105 118 149]


In [11]:
a = np.array([10,39,59,50,60])
b = np.array([30,50,46,68,89])
result = np.subtract(a,b)
print(result)

[-20 -11  13 -18 -29]


In [12]:
a = np.array([10,39,59,50,60])
b = np.array([30,50,46,68,89])
result = np.multiply(a,b)
print(result)

[ 300 1950 2714 3400 5340]


In [13]:
a = np.array([10,39,59,50,60])
b = np.array([30,50,46,68,89])
result = np.divide(a,b)
print(result)

[0.33333333 0.78       1.2826087  0.73529412 0.6741573 ]


In [15]:
a = np.array([10,39,59,50,60])
b = np.array([3,2,2,2,2])
result = np.power(a,b)
print(result)

[1000 1521 3481 2500 3600]


In [17]:
a = np.array([10,39,59,50,60])
b = np.array([3,5,4,6,8])
result = np.mod(a,b)
print(result)

[1 4 3 2 4]


In [18]:
import pandas as pd

In [21]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [23]:
list = ['Google','AWS','Cloud','Software','Statistics','DSA']
df = pd.DataFrame(list)
print(df)

            0
0      Google
1         AWS
2       Cloud
3    Software
4  Statistics
5         DSA


In [24]:
data = {
    'A':np.array([2,4,5]),
    'B':np.array([4,7,8]),
    'C':np.array([6,9,1])
}
df = pd.DataFrame(data)
print(df)

   A  B  C
0  2  4  6
1  4  7  9
2  5  8  1


In [27]:
data = [
    {'name':'Ankita','Degree':'Btech','Cgpa':7.0},
    {'name':'Karishma','Degree':'MBA','Cgpa':9.4},
    {'name':'Ujjwal','Degree':'Btech','Cgpa':9.8}
]
df = pd.DataFrame(data)
print(df)

       name Degree  Cgpa
0    Ankita  Btech   7.0
1  Karishma    MBA   9.4
2    Ujjwal  Btech   9.8
